tosca_definitions_version: tosca_simple_yaml_1_3

imports:
  - /library/steampunk.valves/main.yaml
  - /library/steampunk.gears/main.yaml
  - library/types.yaml

topology_template:
  node_templates:
    dummy:
      type: tosca.nodes.Root
