---
- hosts: all
  gather_facts: false

  tasks:
    - name: Make the location
      file:
        path: /tmp/playing-opera/hello
        recurse: true
        state: directory

    - name: Ansible was here
      file:
        path: /tmp/playing-opera/hello/hello.txt
        state: touch
