- hosts: all
  gather_facts: false

  tasks:
    - name: Say pre_configure_target
      debug:
        msg: "pre_configure_target"

    - name: Set attribute
      set_stats:
        data:
          pre_configure_target_attribute: "This is pre configure target attribute"
