name: nightly

on:
  schedule:
    - cron: '0 3 * * *'

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout to stable branch
        uses: actions/checkout@v3
        with:
          ref: stable

      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.4

      - name: Install the latest released opera package
        run: |
          pip install --upgrade pip
          pip install wheel
          pip install opera

      - name: Run integration tests
        run: ./dev.sh integration
